In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import yfinance as yf
import pandas_ta as ta


In [5]:
data = yf.download(tickers = 'ADANIPOWER.NS', start = '2012-03-11')
data.head(10)

[*********************100%***********************]  1 of 1 completed


Open       High        Low      Close  Adj Close    Volume
Date                                                                       
2012-03-12  76.949997  77.900002  74.800003  75.099998  75.099998   4115129
2012-03-13  76.500000  77.250000  74.500000  74.900002  74.900002   5907813
2012-03-14  75.949997  78.000000  74.800003  75.000000  75.000000   4893683
2012-03-15  75.599998  76.900002  73.099998  75.650002  75.650002   6983349
2012-03-16  76.650002  78.849998  72.250000  72.900002  72.900002  18586087
2012-03-19  72.900002  73.949997  68.650002  69.300003  69.300003   9894484
2012-03-20  69.699997  70.349998  65.800003  66.500000  66.500000  11320578
2012-03-21  68.000000  68.599998  65.300003  67.750000  67.750000  12994399
2012-03-22  67.750000  67.949997  62.000000  64.449997  64.449997  10348597
2012-03-23  65.050003  68.849998  64.449997  68.150002  68.150002  10689488

In [6]:
# Adding indicators
data['RSI']=ta.rsi(data.Close, length=15)
data['EMAF']=ta.ema(data.Close, length=20)
data['EMAM']=ta.ema(data.Close, length=100)
data['EMAS']=ta.ema(data.Close, length=150)

data['Target'] = data['Adj Close']-data.Open
data['Target'] = data['Target'].shift(-1)

data['TargetClass'] = [1 if data.Target[i]>0 else 0 for i in range(len(data))]

data['TargetNextClose'] = data['Adj Close'].shift(-1)

data.dropna(inplace=True)
data.reset_index(inplace = True)
data.drop(['Volume', 'Close', 'Date'], axis=1, inplace=True)

In [7]:
data_set = data.iloc[:, 0:11]#.values
pd.set_option('display.max_columns', None)

data_set.head(20)
#print(data_set.shape)
#print(data.shape)
#print(type(data_set))

Open       High        Low  Adj Close        RSI       EMAF  \
0   51.000000  52.349998  48.900002  49.549999  52.639498  49.730550   
1   49.950001  50.400002  48.500000  49.200001  51.534551  49.680021   
2   49.450001  50.599998  49.250000  50.150002  54.322912  49.724781   
3   51.099998  51.099998  48.500000  48.950001  50.398663  49.650993   
4   47.549999  48.599998  47.000000  48.200001  48.073149  49.512803   
5   48.299999  49.200001  47.549999  47.900002  47.140925  49.359203   
6   48.150002  48.849998  47.299999  47.750000  46.656233  49.205946   
7   47.750000  48.500000  47.000000  47.849998  47.045130  49.076808   
8   47.950001  48.299999  46.299999  48.000000  47.658416  48.974255   
9   48.150002  48.650002  47.549999  48.200001  48.510294  48.900516   
10  48.049999  49.799999  47.900002  49.400002  53.387243  48.948086   
11  50.000000  50.450001  49.049999  49.450001  53.583509  48.995888   
12  49.250000  49.849998  48.549999  48.750000  50.400254  48.972470   
13  48.500000  49.900002  48.500000  49.650002  54.152281  49.036997   
14  50.000000  50.400002  49.200001  50.000000  55.553201  49.128711   
15  49.400002  49.700001  48.900002  49.299999  52.139261  49.145024   
16  49.549999  49.849998  48.500000  48.700001  49.353890  49.102641   
17  49.150002  49.150002  47.500000  47.950001  46.058531  48.992866   
18  48.099998  48.849998  47.400002  48.400002  48.278602  48.936403   
19  48.500000  49.400002  46.599998  47.500000  44.365819  48.799602   

         EMAM       EMAS    Target  TargetClass  TargetNextClose  
0   49.873962  52.429333 -0.750000            0        49.200001  
1   49.860617  52.386561  0.700001            1        50.150002  
2   49.866347  52.356937 -2.149998            0        48.950001  
3   49.848202  52.311812  0.650002            1        48.200001  
4   49.815564  52.257351 -0.399998            0        47.900002  
5   49.777632  52.199638 -0.400002            0        47.750000  
6   49.737481  52.140702  0.099998            1        47.849998  
7   49.700105  52.083872  0.049999            1        48.000000  
8   49.666440  52.029781  0.049999            1        48.200001  
9   49.637401  51.979055  1.350002            1        49.400002  
10  49.632700  51.944896 -0.549999            0        49.450001  
11  49.629082  51.911851 -0.500000            0        48.750000  
12  49.611675  51.869972  1.150002            1        49.650002  
13  49.612434  51.840568  0.000000            0        50.000000  
14  49.620108  51.816190 -0.100002            0        49.299999  
15  49.613770  51.782863 -0.849998            0        48.700001  
16  49.595675  51.742030 -1.200001            0        47.950001  
17  49.563088  51.691805  0.300003            1        48.400002  
18  49.540056  51.648205 -1.000000            0        47.500000  
19  49.499659  51.593262 -0.200001            0        47.500000

In [8]:
#Target column Categories
#y =[1 if data.Open[i]>data.Close[i] else 0 for i in range(0, len(data))]
#yi = [data.Open[i]-data.Close[i] for i in range(0, len(data))]
#print(yi)
#print(len(yi))

In [9]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range=(0,1))
data_set_scaled = sc.fit_transform(data_set)
print(data_set_scaled)

[[0.08765874 0.08705571 0.08348795 ... 0.4509034  0.         0.08092555]
 [0.08506966 0.08237272 0.08249846 ... 0.47368423 1.         0.08320346]
 [0.08383677 0.08285302 0.08435374 ... 0.42890815 0.         0.0803261 ]
 ...
 [0.4704722  0.47526417 0.46542982 ... 0.50746254 1.         0.47644166]
 [0.48292443 0.48006724 0.48324058 ... 0.60722717 1.         0.50209808]
 [0.49365058 0.50132086 0.4943723  ... 0.55616647 1.         0.52871358]]


In [10]:
# multiple feature from data provided to the model
X = []
#print(data_set_scaled[0].size)
#data_set_scaled=data_set.values
backcandles = 30
print(data_set_scaled.shape[0])
for j in range(8):#data_set_scaled[0].size):#2 columns are target not X
    X.append([])
    for i in range(backcandles, data_set_scaled.shape[0]):#backcandles+2
        X[j].append(data_set_scaled[i-backcandles:i, j])

#move axis from 0 to position 2
X=np.moveaxis(X, [0], [2])

#Erase first elements of y because of backcandles to match X length
#del(yi[0:backcandles])
#X, yi = np.array(X), np.array(yi)
# Choose -1 for last column, classification else -2...
X, yi =np.array(X), np.array(data_set_scaled[backcandles:,-1])
y=np.reshape(yi,(len(yi),1))
#y=sc.fit_transform(yi)
#X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
print(X)
print(X.shape)
print(y)
print(y.shape)

2596
[[[0.08765874 0.08705571 0.08348795 ... 0.08691236 0.08677067 0.09550834]
  [0.08506966 0.08237272 0.08249846 ... 0.08677705 0.08672803 0.09536034]
  [0.08383677 0.08285302 0.08435374 ... 0.08689691 0.08674634 0.09525784]
  ...
  [0.08617927 0.08369356 0.08583797 ... 0.08334646 0.08480107 0.0913033 ]
  [0.08716558 0.08981748 0.088188   ... 0.08454541 0.08504416 0.09138973]
  [0.09468623 0.09305955 0.09412493 ... 0.08597448 0.08536783 0.09153688]]

 [[0.08506966 0.08237272 0.08249846 ... 0.08677705 0.08672803 0.09536034]
  [0.08383677 0.08285302 0.08435374 ... 0.08689691 0.08674634 0.09525784]
  [0.08790531 0.08405379 0.08249846 ... 0.08669931 0.08668837 0.09510171]
  ...
  [0.08716558 0.08981748 0.088188   ... 0.08454541 0.08504416 0.09138973]
  [0.09468623 0.09305955 0.09412493 ... 0.08597448 0.08536783 0.09153688]
  [0.09641228 0.09606147 0.09486704 ... 0.08743322 0.08572621 0.09171188]]

 [[0.08383677 0.08285302 0.08435374 ... 0.08689691 0.08674634 0.09525784]
  [0.08790531 0.0

In [11]:
#also comprehensions for X
#X = np.array([data_set_scaled[i-backcandles:i,:4].copy() for i in range(backcandles,len(data_set_scaled))])
#print(X)
#print(X.shape)

In [12]:
# split data into train test sets
splitlimit = int(len(X)*0.8)
print(splitlimit)
X_train, X_test = X[:splitlimit], X[splitlimit:]
y_train, y_test = y[:splitlimit], y[splitlimit:]
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
print(y_train)

2052
(2052, 30, 8)
(514, 30, 8)
(2052, 1)
(514, 1)
[[0.09207529]
 [0.10106702]
 [0.10214602]
 ...
 [0.17755665]
 [0.16688647]
 [0.1770771 ]]


In [18]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers import Dense
from keras.layers import TimeDistributed

import tensorflow as tf
import keras
from keras import optimizers
from keras.callbacks import History
from keras.models import Model
from keras.layers import Dense, Dropout, LSTM, Input, Activation, concatenate
import numpy as np
#tf.random.set_seed(20)
np.random.seed(10)

lstm_input = Input(shape=(backcandles, 8), name='lstm_input')
inputs = LSTM(150, name='first_layer')(lstm_input)
inputs = Dense(1, name='dense_layer')(inputs)
output = Activation('linear', name='output')(inputs)
model = Model(inputs=lstm_input, outputs=output)
adam = optimizers.Adam()
model.compile(optimizer=adam, loss='mse')
model.fit(x=X_train, y=y_train, batch_size=15, epochs=30, shuffle=True, validation_split = 0.1)

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
y_pred = model.predict(X_test)
#y_pred=np.where(y_pred > 0.43, 1,0)
for i in range(10):
    print(y_pred[i], y_test[i])

In [ ]:
plt.figure(figsize=(16,8))
plt.plot(y_test, color = 'black', label = 'Test')
plt.plot(y_pred, color = 'green', label = 'pred')
plt.legend()
plt.show()